{% set version = "r26" %}
package:
    name: msinttypes
    version: {{ version }}

source:
    fn: msinttypes-{{ version }}.zip
    url: https://msinttypes.googlecode.com/files/msinttypes-{{ version }}.zip
    md5: 94c6acec78be290fc72cd01f2755341a

build:
    number: 2
    skip: True  # [not win]

about:
    home: https://code.google.com/archive/p/msinttypes/
    license: BSD-3-Clause
    summary: 'ISO C9x compliant stdint.h and inttypes.h for Microsoft Visual Studio.'

extra:
    recipe-maintainers:
        - janschulz
        - ocefpaf
        - pelson
