
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "JrZbWYW4wEz5IKYwsbabnElGN9St4sYfO7HoPRx+A7h4yWXcfIO9+nz/HK67J0h72WRMem/lx5qX/flr1iX0e8zn3cSH8ujMjuZ5grfQj4PCHqeZvC4gThsxNbQ3iqmjD5LbXf6KYX0b9coyv9uIBsG8GF22GHE5XceQu2Ax4BFGtAwthxZpL3mW+pf3ziuaRABen2ru4RvFBe1WbI/7+k3ev6uvsMmEd5qm4V8/GdNVdl9JmhmXCU16dgiOdNjLSjKWgUKVnqgcMQy/+9zcCrOR8WcpvWHq8kmEBsVFAhL5OL7SX8A309WZJ18prT48XpuX1wF12fnPmOrrJB+2MqGuwyBimaQAlPNOLVgLOfm4eAYJJQHzzFiPZXy2xD3v1y1QkxHFrsrYMrB6fcVfTKW/Vte+oIv5RZQQh2O9NT0mCLuitsZ4x06jWtvPQBTpe5fX2TTIESfsxxRdkzIei/34jlXYaExfzGuwSI758nk0HFOI4O3A/UGDujANd9RxomkecSI0qFamBvkJcQ7He9ucVol6G+OKPm1HY46ysxPajkkbvRCw+Jf3I7kc2pFJ23bfzW5KgY48BK0+FHjE6u8lHjzu6BItSXQ/JV9YQiVUeRiSQbusANAF4B3op77qzwP/N+3LO+3K1pzYnkjHPLsDT6yRvMqF4Yrl0NoyFmg="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
