travis:
  secure:
    BINSTAR_TOKEN: Wne+OSP4OmpIdELUmScwK80AwDOvzw+0xeCWiw+vGF7DBLQeqc7cZeR3v0dDbT+rSVpt7Ph5w4gZo3CgYKuTO6r8+8wRNOAnU6llxiw/AjQlHCl7BYTkr8oeQiejydvPM+SmA20BTmYUxhaL0xtmBNumFoCQMp3TbjP2YZQle2C+Z04v1VkOJVYk6mGLkPf8c6ghmgNQNqfDrBeiproKpZEzo74CPvbjH8TTHqnCdQ3x82zmIZYQsRzh8B/qo1pyzQv7fd3J2JcnGpJAhh940o1MfOlEfkU5/MwrdIqQBpUz81nC2IAnLejHUhHPt0knIh1M/DvL0t1+rbBQz5qKNuZZCRKTAk9B1we49g3z4w6SryvXNgKGMs9oa/4syCajm0g47GItyCb2YV57HPt/viu/55HG280eXIthqxZUYhc52P/rXdATtmIFKuDUAG7FWTKJxRneOp7DsvoSzoxygohkzbP5TJam0iTilOO8VUURbRSAgz/l8CRHz2ipuqCtr5HIpep2XANuTEezzNiXQtTOYOKI/Te6lQFzAoVTsAXKyGX1OfnvnMy3hBDBbgf/IeJs4a4tsEc97ycEbrYjjQnUXDwzk24OyRUb7ALzZdgKbgJ6a1AteyLTCFgRAEjqGy0RQVE3l4V/p8YKdvFg5y6aP0S2gvdt3wcaELaS+wo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
