travis:
  secure:
    BINSTAR_TOKEN: eC2BYLpANooI5mQ4F/zOLom/RF/id0M202v5l7z99dkmjTpyAcqaIpAOF8Kh1hhVywTi/Q4Ls/nZrdG28VQKN9mB7gXc3aCG44LZq8VnFp3B8VkEly/6ttX40tLQsmMYn4D+Ll9GI44WcElgmZkxMeAMrrDu9WRbo/9mwH7QL5xG2pFUpiJ+f6JHbuxJRJ1wPNWsBUMkGIYauHvJP4cacmRnq4kmjpD69csDVwNWOVd8TkIqcn/ZtbhwT/yMFkXUv8xmfk/wrP/JiXEotkHuHnavammvfzjWjDO6IaKbWXBSbxqxTSeGa4dFeRSKrSG124OV6V5m8qYQxsKMjnwMyUKYKlneuujQsAkRcNXF3pApxWx2gV369gCYi1dBEK08iYkR5XcfeBIsvLo9msjPpprJ38qa3F/wJAYxeRRlGfFX0MAoA/ATSJ2P+AvnzMGFyH/UzaWnP+9qQnUZLboBfw7cXMRFxdgPUWxCfVtjE53b4qq2gSv4OSdSK1BNgF6HzsXmcxPcJFOxqQ0Ijk1HWZhI+HheBe9sM8MNj9Qpf8Nry71T8nThO6DFu6sO5IHOw1xC5U4BpW9j/aG84925FGRRguK9WiFUm0beb1UmS0tJKBX+sR/5baZSQGoQXv6Km/d6Q3c0Iohw24FPzsKUYZB9a4VtPbqdsSRhtTvhqdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
